### ISSUE TITLE
Penambahan element Waktu pada XML

### ISSUE THREAD

**Issue by martanto** [infoBMKG/data-gempabumi#1]
Pada https://data.bmkg.go.id/DataMKG/TEWS/autogempa.xml, yang memiliki format sebagai berikut:
```xml
<Infogempa>
    <gempa>
        <Tanggal>17 Apr 2021</Tanggal>
        <Jam>08:04:52 WIB</Jam>
        <point>
            <coordinates>5.05,95.31</coordinates>
        </point>
        <Lintang>5.05 LU</Lintang>
        <Bujur>95.31 BT</Bujur>
        <Magnitude>5.5</Magnitude>
        <Kedalaman>93 km</Kedalaman>
        <Wilayah>Pusat gempa berada dilaut 39 km BaratDaya JANTHO-ACEHBESAR</Wilayah>
        <Potensi>Gempa ini dirasakan untuk diteruskan pada masyarakat</Potensi>
        <Dirasakan>IV Banda Aceh, III Pidie Jaya, III Nagan Raya, III Lhokseumawe, III Calang</Dirasakan>
        <Shakemap>20210417080452.mmi.jpg</Shakemap>
    </gempa>
</Infogempa>
```

**Problems:**
1. Penggunaan element Tanggal tidak diketahui jenis format tanggal yang dipakai. Referensi:
    * https://www.php.net/manual/en/function.date.php
    * https://www.iso.org/iso-8601-date-and-time-format.html
2. Begitu juga dengan format Jam, yang menyertakan WIB pada akhir format.

**Saran:**
1. Penambahan element Waktu, dengan format: `Y-m-d H:i:s`. Contoh: `2021-02-03 23:59:59`
2. Penambahan element ZonaWaktu, dengan nilai `WIB, WITA, WIT`

Sehingga format XML yang baru akan berubah menjadi seperti:
```xml
<Infogempa>
    <gempa>
        <Tanggal>17 Apr 2021</Tanggal>
        <Jam>08:04:52 WIB</Jam>
        <Waktu>2021-04-17 08:04:52</Waktu>
        <ZonaWaktu>WIB</ZonaWaktu>
        <point>
            <coordinates>5.05,95.31</coordinates>
        </point>
        <Lintang>5.05 LU</Lintang>
        <Bujur>95.31 BT</Bujur>
        <Magnitude>5.5</Magnitude>
        <Kedalaman>93 km</Kedalaman>
        <Wilayah>Pusat gempa berada dilaut 39 km BaratDaya JANTHO-ACEHBESAR</Wilayah>
        <Potensi>Gempa ini dirasakan untuk diteruskan pada masyarakat</Potensi>
        <Dirasakan>IV Banda Aceh, III Pidie Jaya, III Nagan Raya, III Lhokseumawe, III Calang</Dirasakan>
        <Shakemap>20210417080452.mmi.jpg</Shakemap>
    </gempa>
</Infogempa>
```

Penambahan element ini tidak akan mengganggu sistem yang telah ada dan hal ini akan mempermudah integrasi dengan bahasa pemrograman lain.

**Comment by raksakaindra** [comment]
Saat ini sudah kami tambahakan _key_ `DateTime` dalam format UTC (+00:00) sesuai dengan ISO 8601 pada dokumentasi Github ini dan pada data gempa berikut:
1. [https://data.bmkg.go.id/DataMKG/TEWS/autogempa.xml](https://data.bmkg.go.id/DataMKG/TEWS/autogempa.xml)
2. [https://data.bmkg.go.id/DataMKG/TEWS/gempaterkini.xml](https://data.bmkg.go.id/DataMKG/TEWS/gempaterkini.xml)
3. [https://data.bmkg.go.id/DataMKG/TEWS/gempadirasakan.xml](https://data.bmkg.go.id/DataMKG/TEWS/gempadirasakan.xml)

Terima kasih @martanto atas masukannya. 👍
