### ISSUE TITLE
DateTime ISO:8601 Salah Tanggal

### ISSUE THREAD

**Issue by josefmtd** [infoBMKG/data-gempabumi#5]
Pada data gempaterkini.json / gempaterkini.xml ataupun gempadirasakan.json / gempadirasakan.xml menggunakan tanggal akses dan bukan tanggal kejadian gempa.

![image](https://user-images.githubusercontent.com/28034179/123738745-9257f580-d8cf-11eb-9b8d-3a4778d87e0a.png)

**Comment by raksakaindra** [comment]
@josefmtd Saat ini sudah kami perbaiki untuk penanggalan ```DateTime``` ISO:8601. Silakan dapat dicek kembali.
Terima kasih. 👍
